parlametria/leggoR

- R/config/environment_camara.json
> Substitui comissão especial por regex

- R/analyzer.R
- R/camara_analyzer.R
- R/config/environment_camara.json
- R/config/environment_senado.json
- R/congresso-lib.R
- R/senado_analyzer.R
Verifica na camara se a proposição foi vetada ou virou lei
> 740 virou lei

- R/relatorias.R
> resolve bug de relatoria do senado (issue-310)

- DESCRIPTION
- R/analyzer.R
- R/config/environment_congresso.json
- R/export_data.R
- R/proposicoes.R
- R/utils.R
- scripts/fetch_updated_bills_data.R
Requer: https://github.com/analytics-ufcg/leggo-backend/pull/78
> 908 nivel importancia eventos

- data/tabela_geral_ids_casa.csv
Atualiza csv com proposições com mais de um tema.
> Adiciona mais de um tema por pl no csv

- R/relatorias.R
- data/tabela_geral_ids_casa.csv
Reverts analytics-ufcg/leggoR#365
> Revert "Adiciona a pl 1917/2015"

- R/config/environment_camara.json
> Conserta regex do parecer

- R/analyzer.R
Exemplo, da data '2019-05-06' a '2019-05-10'
> Quando não tinha nada na tabela de pauta dava erro

- R/comissoes.R
> Id dos senadores

- R/analyzer.R
- scripts/fetch_agenda.R
Precisa das modificações em: https://github.com/analytics-ufcg/leggo-geral/pull/4
> Extrator de pautas

- R/camara_analyzer.R
> Pega a apreciação pela chamada a versão 1 da api

- .gitlab-ci.yml
de acordo com a solução encontrada aqui: https://gitlab.com/gitlab-org/gitlab-ce/issues/64959
> Corrige problema do gitlab runner

- data/tabela_geral_ids_casa.csv
https://github.com/analytics-ufcg/leggo-backend/pull/122
> Adiciona o id do Senado da reforma da previdencia

- R/analyzer.R
- R/proposicoes.R
- R/utils.R
- scripts/update_leggo_data.R
- tests/testthat/test-temperaturas.R
Algumas semanas estavam sem temperatura, como a semana do dia 21/07/2019
> 1383 bug temperatura

- R/analyzer.R
- R/config/environment_camara.json
- R/config/environment_congresso.json
- R/config/environment_senado.json
- R/congresso-lib.R
- R/senado_analyzer.R
Ajeita o progresso da nova previdência e o status dela
> 1487 progresso previdencia

- R/constants.R
- R/export_data.R
- R/requerimentos.R
Precisa dessa branch do rcongresso: https://github.com/analytics-ufcg/rcongresso/pull/169
> 1567 erro 429 atualizacao dados

- R/constants.R
- R/export_data.R
- R/export_emendas.R
- R/requerimentos.R
Depende de: https://github.com/analytics-ufcg/rcongresso/pull/170
> Eficiencia fetch emendas

- R/agendas.R
- R/analyzer.R
- scripts/fetch_agenda.R
Depende de: https://github.com/analytics-ufcg/rcongresso/pull/171
> 1615 script pautas quebrado

- R/prepare_coautorias_data.R
- Reduz tamanho dos dataframes durante o processamento de coautorias
- Utiliza o garbage collection para melhorar uso de memória
- Simplifica processo usando menos joins
- É possível monitorar o quanto de memória um container está consumindo usando: `docker stats`
> Otimiza processamento de coautorias

- scripts/anotacoes/export_anotacoes.R
- scripts/anotacoes/process_anotacoes.R
**Mudanças propostas neste PR:**
- Adiciona módulo de anotações, contendo um script que baixa e processa os dados de anotações e outro para exportar esses dados em um arquivo .csv
Url com a versão dev com a lista das anotações: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQIC9sm_jTojACKqzF17nPU8qiQRmWSeaKDOeRuxkLnhSZwOwdx0GpgGflpJigM3-N_KOPBz85-wR_u/pub?gid=0&single=true&output=csv".
> Adiciona módulo de anotações de proposições

- .gitlab-ci.yml
- R/config/environment_congresso.json
- R/utils.R
- scripts/proposicoes/export_proposicoes_interesse_congresso_remoto.R
- scripts/proposicoes/fetcher_proposicao.R
- scripts/proposicoes/process_proposicao.R
O resultado da planilha pode ser conferido neste [link](https://docs.google.com/spreadsheets/d/1IHOcZYsHXgRkOJp54MR4AxnUNV4efudapEkfbsLrInQ/edit?usp=sharing).
Exemplos de planilhas de entrada:
- url para csv com novas proposições (sem ids e formato esperado pelo leggo): "https://docs.google.com/spreadsheets/d/e/2PACX-1vS02ZVq32CrWyCLfFu24hL_KpzKCZat9lyv5IkO5s5J9hJCalYlWJaaZNsVIFwGbrCdQqtePnWrT_y9/pub?gid=1306016971&single=true&output=csv"
- url para csv com proposições já usadas pelo leggo: https://docs.google.com/spreadsheets/d/e/2PACX-1vS4PiPHNO1rUEgY60q4nD7sUmx99JssruW5JSl0Mb0kGzvdS7IWNG_DdJf35GBye2ua0XZv4hP0OJ7K/pub?gid=0&single=true&output=csv
> Cria módulo que mapeia proposições à ids, formata dataframe e une planilhas

- R/export_data.R
- Adiciona checagem para processamento de proposições sem ids
> Adiciona checagem para processamento de proposições sem ids

- scripts/proposicoes/process_proposicao.R
**Mudanças deste PR:**
- Adiciona o id aos dados que serão processados pelo congresso caso não estejam preenchidos na planilha;
- Adiciona tratamentos de exceções ao baixar dados de temas, ementa e nome formal da proposição;
> Adiciona ids faltantes às proposições

- scripts/anotacoes/process_anotacoes.R
- Melhora script para processar somente anotações válidas que possuem data de criação, de modificação, título e texto.
> Trata casos onde não há texto nem titulo

- R/export_data.R
- Adiciona checagem de NA na criação do dataframe de progresso
> Adiciona checagem de NA na criação do dataframe de progresso

- scripts/entidades/export_entidades.R
- scripts/entidades/process_entidades.R
- scripts/parlamentares/export_parlamentares.R
- scripts/parlamentares/fetcher_parlamentares.R
- scripts/parlamentares/process_parlamentares.R
- scripts/parlamentares/update_parlamentares.R
**Mudanças propostas neste PR:**
- Adiciona módulo de parlamentares que baixa todos os dados das legislaturas 51 a 56 ou apenas atualiza os dados dos parlamentares das duas últimas legs (55 e 56).
> Adiciona módulo de parlamentares

- R/prepare_coautorias_data.R
- scripts/documentos/export_coautorias.R
- Adiciona coluna com o peso do autor no documento
> Adiciona coluna com o peso do autor no documento

- scripts/documentos/export_atuacao.R
- scripts/process_leggo_data.R
- Corrige informações dos parlamentares na tabela de atuação realizando um cruzamento com entidades
> Corrige informações dos parlamentares na tabela de atuação

- scripts/interesses/process_lista_pls_interesse.R
- Adiciona coluna tema_slug no csv de interesses, com os temas processados e "url-záveis" (minúsculos, sem acentos, sem espaços).
> Adiciona coluna tema_slug

- Dockerfile
- R/analyzer.R
- R/export_data.R
- scripts/fetch_updated_bills_data.R
- scripts/fix-temperatura.R
- Modificando o id_leggo para concatenação de id_camara e id_senado.
> modificando valor do id_leggo para concatenaçao

- R/relatorias.R
-  Adiciona checagem para quando o partido e a uf do relator não estiver disponível.
- Bug identificado na PL 4811/2005 (id_camara 275708)
>  Adiciona checagem para quando o partido e a uf do relator não estiver disponível

- R/relatorias.R
- scripts/interesses/process_lista_pls_interesse.R
- tests/testthat/test-progresso.R
- Resolve bug no processamento de proposições sem o nome do relator.
- Faz merge com a branch master.
- A proposição que dava erro e motivou a correção: id_camara 2217142 id_senado NA
> Resolve bug no processamento de proposições sem o nome do relator

- scripts/proposicoes/process_proposicao.R
- Trata pontos no número da proposição;
- Retira explicacao_projeto do preenchimento automático.
> Trata pontos no número da proposição e remove preenchimento de ementa

- R/relatorias.R
- tests/testthat/test-atuacao.R
- tests/testthat/test-proposicoes.R
- Altera regex para separação entre partido e estado nas informações do relator
- Corrige testes
> Altera regex para separação entre partido e estado nas informações do relator

- R/export_data.R
- tests/testthat/test-atuacao.R
- tests/testthat/test-proposicoes.R
- Adiciona o último status da proposição ao csv de proposições.
> Adiciona coluna status ao csv de proposições

- scripts/interesses/process_lista_pls_interesse.R
Adiciona captura de coluna com a descrição das agendas.
> 2223 - Captura descrição da agenda

- R/config/environment_senado.json
- R/congresso-lib.R
- R/senado_analyzer.R
- Melhora detecção de evento remetido à sanção no senado;
- Adiciona fim à fase de Sanção/Veto quando a proposição é transformada em lei.
> Adiciona código que melhora detecção de remetida à sanção

- R/config/environment_senado.json
- R/congresso-lib.R
- R/senado_analyzer.R
- scripts/proposicoes/destaques/export_destaques.R
- scripts/proposicoes/destaques/process_criterio_aprovada_em_uma_casa.R
- scripts/proposicoes/destaques/process_destaques.R
- Implementa process e export de proposicoes_destaques;
- Implementa função que processa o critério 1 : proposições que foram aprovadas em pelo menos uma casa;
- Adiciona mais regras ao regex de detecção de evento remetida à sanção.
> Adiciona critério 1 ao processamento de proposições de destaque

- scripts/proposicoes/destaques/process_criterio_pressao_alta.R
- scripts/proposicoes/destaques/process_destaques.R
- Adiciona processamento do critério 5 (proposições com alta pressão)
> Adiciona processamento do critério 5 (proposições com alta pressão)

- R/config/environment_congresso.json
- scripts/entidades/process_entidades.R
- Adiciona autores especiais de proposições
- Resolve atores para as proposições:
https://www25.senado.leg.br/web/atividade/materias/-/materia/127764
https://www25.senado.leg.br/web/atividade/materias/-/materia/126119
> Adiciona autores especiais de proposições

- scripts/proposicoes/destaques/process_criterio_aprovada_em_uma_casa.R
- Adiciona filtro de ano mínimo nas proposições do critério 'aprovada em uma casa'.
> Adiciona filtro de tempo no critério 'aprovada em uma casa'

- scripts/proposicoes/destaques/export_destaques.R
- scripts/proposicoes/destaques/process_criterio_avancou_comissoes.R
- scripts/proposicoes/destaques/process_destaques.R
- Adiciona comissões onde a proposição avançou
- Seleciona as colunas próprias para importação no bd
> Formata CSV de proposições em destaque para importação

- R/prepare_coautorias_data.R
> Adiciona sigla ao csv de autorias

- Dockerfile
- scripts/governismo/export_governismo.R
- scripts/governismo/process_governismo.R
- Adiciona módulo de governismo
- Cria arquivo para exportação do csv de governismo
- Adiciona dependências do pacote perfilparlamentar ao Dockerfile
> Adiciona módulo de governismo

- R/config/environment_camara.json
Regexes foram aprimorados, outros eventos foram eliminados e outros criados.
> Revisão 01 dos regexes dos eventos da câmara

- Dockerfile
- scripts/votos/analyzer_votos.R
- scripts/votos/export_votos.R
- scripts/votos/fetcher_votos.R
- Adiciona script que executa e salva os dados de votações e votos;
- Altera Dockerfile para instalar pacote perfilparlamentar.
> Adiciona processamento de votos e votações 

- R/config/environment_camara.json
- PR já revisado https://github.com/parlametria/leggoR/pull/659
> Adiciona modificação da revisão de mais eventos

- R/config/environment_congresso.json
Closes #662 
Adiciona título para os novos eventos criados por Henrique.
> Adicionando arquivo com os novos títulos

- R/analyzer.R
- R/congresso-lib.R
- tests/testthat/test-temperaturas.R
Exemplo de proposição 
id_camara: 623634
> Trata casos de proposições com tramitações sem data

- R/comissoes.R
- scripts/fetch_updated_bills_data.R
- Modifica endpoint de composição das comissões na Câmara para a nova, com histórico.
> Adiciona histórico de comissões para a Câmara

- inst/extdata/parlamentares.csv
- scripts/parlamentares/update_parlamentares.R
- Atualiza csv de parlamentares do repositório
- Atualiza csv do repositório durante a execução do update_parlamentares.R
> Atualiza csv de parlamentares do repositório

- R/analyzer.R
- tests/testthat/test-analyzer.R
- Adiciona tratamento para evitar títulos de indeferimentos com NA e eventos duplicados
NA no título: Proposição testada: id_camara 2270800
Eventos duplicados: Proposição testada: id_camara 2229708
Resolve a issue https://github.com/parlametria/leggo-painel/issues/294
> Adiciona tratamento para evitar títulos de indeferimentos com NA e eventos duplicados

- R/analyzer.R
- scripts/orientacoes/export_orientacoes.R
- scripts/votos/analyzer_votos.R
- scripts/votos/export_votos.R
- scripts/votos/fetcher_votos.R
- Adicionou parâmetros para leitura de arquivos csv
- Reduziu o número de anos para download deixando apenas 2021
- Deve ser revisado em conjunto com o PR https://github.com/parlametria/perfil-parlamentarR/pull/26
> Revisa scripts de captura de votos e orientações

- scripts/votacoes_sumarizadas/export_votacoes_sumarizadas.R
- scripts/votacoes_sumarizadas/process_votacoes_sumarizadas.R
- Adiciona parâmetro de orientações para geração dos dados de votações sumarizadas
- Devem ser revisados em conjunto os PRs: https://github.com/parlametria/perfil-parlamentarR/pull/29, https://github.com/parlametria/leggoR/pull/682, https://github.com/parlametria/leggo-geral/pull/55
> Adiciona parâmetro de orientações para geração dos dados de votações sumarizadas

- R/export_data.R
- R/parlamentares.R
- Adiciona sigla no processamento dos metadados das proposições
- Depende da revisão do PR https://github.com/parlametria/leggoR/pull/686
> Adiciona sigla no processamento dos metadados das proposições

- docker-compose.yml
- Conserta build do pipeline alterando critério para captura da variável de ambiente
> Conserta build do pipeline 

- R/export_data.R
- Trata problema de não detecção de locais atuais e progressos quando não houve modificação na proposição e não há dados para esta proposição nos csvs de locais e progressos.
> Conserta locais atuais e progressos não recuperados

- scripts/proposicoes/destaques/process_criterio_pressao_alta.R
- scripts/proposicoes/destaques/process_criterio_requerimento_urgencia.R
- Conserta warning no processamento do critério de pressão alta e no de requerimento de urgência.
> Conserta warning na geração das proposições em destaque

- scripts/logs/bot_parlametria.R
- scripts/proposicoes/apensadas/export_apensadas.R
- Adicionando função que cria mensagem de log com as informações das proposições apensadas e envia a mensagem para o bot;
> 2524 Enviar proposições apensadas anexadas pelo bot do telegram

- R/agendas.R
- R/comissoes.R
- Corrige chamada à função do rcongresso
- Melhora retorno de tibble vazio
- Depende da versão e revisão do PR no rcongresso: https://github.com/analytics-ufcg/rcongresso/pull/197
> Corrige chamada à função do rcongresso

- scripts/logs/bot_parlametria.R
- Corrige coluna exibida no log das proposições apensadas
> Corrige coluna exibida no log das proposições apensadas

- R/etapas.R
- R/export_data.R
- Processa proposições que ainda não estão presentes no csv de proposições
- Adiciona flag para forçar processamento de proposições
> Processa proposições que ainda não estão presentes no csv de proposições

- R/export_data.R
> Diminui número máximo de tentativas em processamento de proposições

- scripts/interesses/process_lista_pls_interesse.R
- Adiciona checagem e preenchimento de proposições repetidas em diferentes painéis. Isto acontece quando o GT adiciona uma proposição com ambos os ids preenchidos (camara e senado) e em outra linha adiciona uma nova com apenas um dos ids preenchidos.
> Implementa lógica de checagem de proposições

- scripts/proposicoes/destaques/fetcher_criterio_mais_comentadas_twitter.R
Altera a ULR do hrroku para apontar para a nova api.
> Altera urls antigas
