- R/tramitacoes.R
A API da câmara mudou `id` pro `cod`, então:
- Troca nome da coluna de `id_tipo_tramitacao` para `cod_tipo_tramitacao`
> Ajeita fetch_tramitacao_camara

- R/tramitacoes.R
#341 
Tendo em vista que em alguns casos como emendas há bem mais links do que linhas na tramitação eu decedi por não adicionar essas várias linhas a mais a tabela de tramitação da proposição, caso o usuário necessite dos links para os documentos ele poderá utilizar da função: extract_links_proposicao_senado()
> Remove links de inteiro teor do senado

- .gitlab-ci.yml
- R/export_emendas.R
- R/proposicoes.R
- R/textos_proposicao.R
- Refatora função get_emendas e outras funções que chamavam o fetch_emendas do rcongresso no pacote agoradigital, adequando-as ao novo padrão da chamada do fetch_emendas do rcongresso:
+ Removendo parâmetros sigla, ano e número, que não são mais necessários
+ Eliminando a chamada à função fetch_proposicao para pegar a sigla, ano e numero, não mais necessários.
- Necessita [desse PR do rcongresso](https://github.com/analytics-ufcg/rcongresso/pull/178)
- Para testar esse PR, deve-se fazer chamadas ao fetch_emendas e o resultado deve bater com o encontrado na página da proposição na Câmara. Um exemplo curto é a da Lei do FUNDEB na Câmara, cujo id é 1198512
> Refatora fetch emendas camara

- R/proposicoes.R
- scripts/interesses/process_lista_pls_interesse.R
- tests/testthat/test-analyzer.R
- Captura nome do interesse direto da tabela com listagem dos interesses para processamento.
- Pode ser avaliada considerando a versão master do [leggo-geral](https://github.com/parlametria/leggo-geral)
- Foi desenvolvido usando a tabela de desenvolvimento:
URL_INTERESSES="https://docs.google.com/spreadsheets/d/e/2PACX-1vTOdLk1wxJsekjGF5alyD0AP25wVtpnq0QTy6IZTebY_WSiiAF6Any-_BWRTpcerTHHW4zJL3Y9hHpf/pub?gid=0&single=true&output=csv"
- Após revisão e aprovação será necessário adicionar a coluna "nome" na planilha de interesses usada em produção.
> Adiciona coluna com nome do interesse ao csv com o mapeamento dos interesses

- scripts/interesses/process_lista_pls_interesse.R
- scripts/proposicoes/export_proposicoes_interesse_congresso_remoto.R
- scripts/proposicoes/process_proposicao.R
**Mudanças deste PR**
- Adiciona funções que preenchem dados faltosos de nome formal, tema e explicação do projeto (ementa);
- Altera script que exporta os dados da planilha gerada a partir do quadro da pulso e das proposições de interesse do congresso remoto, adicionando novo parâmetro com a url das proposições do senado. Exemplo de chamada do script:
```
Rscript export_proposicoes_interesse_congresso_remoto.R -c  "https://docs.google.com/spreadsheets/d/e/2PACX-1vRajrEzcuVDEYKR8HqHY7Mlo87jxslgwrbQzQpxr9htAdaGGQ1KDnQtgx6LBFufEQ/pub?gid=325050673&single=true&output=csv" -s "https://docs.google.com/spreadsheets/d/e/2PACX-1vRajrEzcuVDEYKR8HqHY7Mlo87jxslgwrbQzQpxr9htAdaGGQ1KDnQtgx6LBFufEQ/pub?gid=1946524948&single=true&output=csv"  -p …
```
> Adiciona preenchimento de informações faltosos

- scripts/anotacoes/export_anotacoes.R
- scripts/anotacoes/process_anotacoes.R
**Mudanças deste PR**:
- Modificar script que processa os dados de insights, adicionando uma lista com o dataframe de insights gerais (que não possuem nenhuma proposição associada) e de insights_especificos;
- Alterar script que exporta esses dados, adicionando argumento de caminho para pasta destino que conterá os arquivos `anotacoes_gerais.csv` e `anotacoes_especificas.csv`.
**OBS:** A url com a lista de anotações versão dev está aqui para auxiliar nos testes: https://docs.google.com/spreadsheets/d/e/2PACX-1vQIC9sm_jTojACKqzF17nPU8qiQRmWSeaKDOeRuxkLnhSZwOwdx0GpgGflpJigM3-N_KOPBz85-wR_u/pub?gid=0&single=true&output=csv
> Adiciona anotações gerais ao leggo

- R/config/environment_senado.json
- R/prepare_coautorias_data.R
- R/proposicoes.R
- scripts/documentos/export_coautorias.R
- Passa a considerar documentos a partir de qualquer data nos dados de autorias. Antes havia um filtro de data.
- Considera o filtro de data apenas para os dados sumarizados de coautorias (nodes e edges consequentemente)
- Passa a usar coluna com a classificação do tipo de documento disponibilizada pelo Senado. Houve melhora na classificação de proposições (PECs principalmente).
> Melhora processamento de autorias e classificação de documentos para o Senado

- Dockerfile
- Melhora ordem do build de dependências da imagem do leggoR
- Para testar é preciso executar um `docker-compose build` na raiz do repositório
> Melhora ordem do build de dependências da imagem do leggoR

- R/congresso-lib.R
- R/senado_analyzer.R
- Cria função para corrigir detecção de eventos duplicados de apresentação de projetos numa mesma casa
- Corrige detecção da fase atual evitando filtro incorreto da fase global
- Evita ignorar eventos de MPVs após a virada de casa
Bugs que foram analisados e corrigidos:
- MPV 927/2020 tramitou no plenario do senado mas o progresso não mostra.
- MPV 983/2020 já voltou para o senado mas o progresso não mostra.
- PL 1444/2020 progresso com problemas (duas fases na camara).
> Corrige bugs no progresso de projetos do Congresso Remoto

- R/export_data.R
- R/read_utils.R
- Conserta erro na importação dos dados de proposições, que fazia a coluna id_leggo ficar NA;
- Conserta problema na geração do csv de autores_leggo, adicionando rowwise na criação do id_leggo.
> Conserta erros que interferiam no mapeamento do novo id_leggo

- R/atuacao.R
- scripts/documentos/export_coautorias.R
- scripts/process_leggo_data.R
**Mudanças deste PR:**
- Remove a duplicação de documentos das Comissões Mistas nas MPVs, retirando estes documentos da atuação na câmara e deixando apenas no senado;
- Adiciona parâmetro de entidades na chamada da função export_autuacao().
Fixes #593
> Retirar documentos duplicados nas Comissões Mistas das MPVs

- R/config/environment_congresso.json
**Mudanças deste PR:**
- Cria mapeamento de Comissão Mista de Planos, Orçamentos Públicos e Fiscalização no regex que adiciona id_autor.
Resolve o problema do id_autor = '3NA'. Isso acontecia para a proposição cujo id_senado é 99699 e como autor a Comissão Mista de Planos, Orçamentos Públicos e Fiscalização, entidade que não tínhamos mapeado ainda.
> Adiciona CMO ao regex que atribui id_autor aos documentos

- R/atuacao.R
- R/config/environment_camara.json
- R/config/environment_senado.json
- R/proposicoes.R
- scripts/documentos/export_atuacao.R
- scripts/documentos/export_coautorias.R
- scripts/process_leggo_data.R
- tests/testthat/test-tipo-documento.R
- Adiciona nova coluna(tipo_acao) nos csvs de atuação e autorias, mantendo os tipos de documentos antigos. 
- Modifica função de adicionar tipo de documento, e classificar o tipo de documentos para autorias a fim de adicionar o tipo de ação e agrupar em Outros os tipos não utilizados.
- Modifica o json da camara e do senado para adicionar novos tipos de ação.
> 2080 Modificar tipo genérico dos documentos

- scripts/proposicoes/destaques/fetcher_criterio_mais_comentadas_twitter.R
- scripts/proposicoes/destaques/process_destaques.R
- Adiciona scripts que baixam os números de tweets por proposição;
- Adiciona processamento que filtra as proposições que possuem mais de um tweet associado.
**OBS:** Revisar o PR #[34](https://github.com/parlametria/leggo-twitter/pull/34) e modificar o endereço da API para o local. (atualmente está a de validação - ainda não foi deploy)
> Adiciona critério 'mais comentadas no twitter'

- scripts/proposicoes/destaques/fetcher_criterio_mais_comentadas_twitter.R
- scripts/proposicoes/destaques/process_criterio_avancou_comissoes.R
- scripts/proposicoes/destaques/process_destaques.R
- Passa a considerar a passagem ou presença na CCJ como critério de seleção para as proposições da câmara.
- Passa a considerar os eventos que aconteceram nos últimos 4 anos.
> Refatora critério de avanço nas comissões

- R/export_data.R
- Na proposição https://www25.senado.leg.br/web/atividade/materias/-/materia/145555 os nomes de alguns autores que são senadores não estavam sendo considerados como senadores na geração do id_autor_parlametria
> Corrige casos especiais de geração do id_autor_parlametria

- scripts/proposicoes/destaques/process_criterio_requerimento_urgencia.R
- Adicionando filtro que considera um período de 4 anos no critério "Urgência requeria" e no critério de "Urgência aprovada"
- Depende da revisão deste PR: [https://github.com/parlametria/leggoR/pull/631]
> 2283 considerar periodo urgencia

- scripts/proposicoes/destaques/process_criterio_requerimento_urgencia.R
- scripts/proposicoes/destaques/process_destaques.R
- Adiciona critérios de urgência ao csv final de destaques
- Adiciona colunas para identificação da casa revisora e da casa de origem
CSV gerado: https://drive.google.com/file/d/1xFoxxCZxgfbLSUdupMELbtBaZXxioOzR/view?usp=sharing
> Adiciona critérios de urgência ao csv final de destaques

- R/analyzer.R
- R/congresso-lib.R
- tests/testthat/test-progresso.R
- Desativa flag do congresso remoto para considerar a nova instalação de comissões
- Proposições usadas para teste
[PL 2895/2020](https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2253704)
[PL 2291/2020](https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2250879)
[PL 2398/2020](https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2251625)
[PL 1380/2020](https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2242646)
[PL 3063/2020](https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2254270)
[PL 3144/2020](https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2254585)
> Altera flag do congresso remoto para considerar a instalação de comissões

- Dockerfile
Há um erro ao fazer a build com docker-compose:
Esse erro pode ser corrido adicionando `--allow-releaseinfo-change` nas linhas do `RUN apt-get update` no Dockerfile.
> Corrige erro na build com docker

- scripts/proposicoes/destaques/process_criterio_pressao_alta.R
- scripts/proposicoes/destaques/process_destaques.R
- Cria função que checa existência do arquivo de pressão antes de calcular o critério de pressão alta. Caso não exista, é retornado um dataframe vazio para este critério;
- Adiciona essa função no processamento das proposições de destaque.
> Adiciona checagem de existência do csv de pressão antes de processar critério de destaque
